SELECT * /* 
     (SELECT COUNT(*) FROM A.F4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'ILLEGAL-REC') AS "ILLEGAL RECOMPENSE"
    ,(SELECT TO_CHAR(SUM(GF_FEE), '$9,999,999,999,999,999.00') FROM A.F4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'ILLEGAL-REC') AS "ILLEGAL-REC FEE TOTAL"
    ,(SELECT COUNT(*) FROM A.F4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'STAN-REC') AS "ARBORIST STANDARD RECOMPENSE"
    ,(SELECT TO_CHAR(SUM(GF_FEE), '$9,999,999,999,999,999.00') FROM A.4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'STAN-REC') AS "STAN-REC FEE TOTAL"
    ,(SELECT COUNT(*) FROM A.F4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'MAX-REC') AS "ARBORIST MAXIMUM RECOMPENSE"
    ,(SELECT TO_CHAR(SUM(GF_FEE), '$9,999,999,999,999,999.00') FROM A.F4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'MAX-REC') AS "MAX-REC FEE TOTAL"
    ,(SELECT COUNT(*) FROM A.F4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'INFRA-REC') AS "ARBORIST INFRA RECOMPENSE"
    ,(SELECT TO_CHAR(SUM(GF_FEE), '$9,999,999,999,999,999.00') FROM A.F4FEEITEM_AUDIT_TRAIL WHERE GF_COD = 'INFRA-REC') AS "INFRA-REC FEE TOTAL"
    */
--FROM DUAL
FROM F4FEEITEM_AUDIT_TRAIL A

LEFT OUTER JOIN BCHCKBOX B ON 1=1
AND A.SERV_PROV_CODE = B.SERV_PROV_CODE
AND A.B1_PER_ID1 = B.B1_PER_ID1
AND A.B1_PER_ID2 = B.B1_PER_ID2
AND A.B1_PER_ID3 = B.B1_PER_ID3
AND B.B1_CHECKBOX_DESC = 'Zoning 1'

WHERE 1=1
AND A.GF_COD IN ('ILLEGAL-REC','STAN-REC','MAX-REC','INFRA-REC')
AND A.GF_FEE_APPLY_DATE >= '01-JAN-13'
AND A.GF_FEE_APPLY_DATE <= '31-DEC-18'
AND A.REC_STATUS = 'A'