SELECT
Distinct ROW_INDEX SignNum,
  (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'Sign Type'
  ) SignType,--*/

  (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'How Secured'
  ) HowSecured,--*/
  
  (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'Category'
  ) Category, --*/
  
  (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'SqFt'
  ) SqFt, --*/
  
  (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'Height of Sign'
  ) Height, --*/

  1
FROM bappspectable_value ASIT
WHERE
		1=1
		AND '{?servProv}' = ASIT.SERV_PROV_CODE
		AND '{?perID1}' = ASIT.B1_PER_ID1
		AND '{?perID2}' = ASIT.B1_PER_ID2
		AND '{?perID3}' = ASIT.B1_PER_ID3
        AND '{?recStat}' = ASIT.REC_STATUS
        
    -- TEST CASE BEGIN
        --AND 'ATLANTA_GA' = ASIT.SERV_PROV_CODE
        --AND '17BL4' = ASIT.B1_PER_ID1
        --AND '00000' = ASIT.B1_PER_ID2
        --AND '00528' = ASIT.B1_PER_ID3
        --AND 'A' = ASIT.REC_STATUS
    -- TEST CASE END
    AND UPPER(ASIT.ATTRIBUTE_VALUE) = 'APPROVED'