SELECT

a.B1_ALT_ID AS CASE,
a.B1_SPECIAL_TEXT AS DESCRIPTION,
b.C6_REFERENCE_TYPE AS SOURCE,
c.G6_ACT_DES AS INSP_TYPE,
c.G6_DOC_DES AS INSP_DISPOSITION,
c.G6_STATUS AS STATUS,
TO_CHAR(c.G6_STATUS_DD, 'MM/DD/YYYY') AS STATUS_DATE,
c.GA_FNAME || ' ' || (CASE WHEN c.GA_MNAME IS NULL THEN '' ELSE c.GA_MNAME || ' ' END) || c.GA_LNAME AS INSPECTOR,
FN_GET_ADDRESS_INFO(A.SERV_PROV_CODE,A.B1_PER_ID1,A.B1_PER_ID2,A.B1_PER_ID3,'Y','PARTADDR_LINE') || ' ' ||
    (SELECT B1_STR_SUFFIX_DIR FROM B3ADDRES B3
    WHERE
        B3.SERV_PROV_CODE = A.SERV_PROV_CODE
    AND B3.B1_PER_ID1 = A.B1_PER_ID1
    AND B3.B1_PER_ID2 = A.B1_PER_ID2
    AND B3.B1_PER_ID3 = A.B1_PER_ID3
    AND B3.B1_PRIMARY_ADDR_FLG = 'Y'
    AND ROWNUM < 2)
        AS ADDRESS,
c.LATITUDE_COORDINATE AS LATITUDE,
c.LONGITUDE_COORDINATE AS LONGITUDE

FROM B1PERMIT a
INNER JOIN BPERMIT_DETAIL b ON
     a.SERV_PROV_CODE = b.SERV_PROV_CODE
AND a.B1_PER_ID1 = b.B1_PER_ID1
AND a.B1_PER_ID2 = b.B1_PER_ID2
AND a.B1_PER_ID3 = b.B1_PER_ID3

INNER JOIN G6ACTION c ON
a.SERV_PROV_CODE = c.SERV_PROV_CODE
AND a.B1_PER_ID1 = c.B1_PER_ID1
AND a.B1_PER_ID2 = c.B1_PER_ID2
AND a.B1_PER_ID3 = c.B1_PER_ID3
AND (c.G6_STATUS_DD >= '01-JAN-17' AND c.G6_STATUS_DD <= '26-JUL-17')
AND c.LATITUDE_COORDINATE IS NOT NULL

WHERE
a.B1_PER_GROUP = 'Enforcement'
AND a.B1_PER_TYPE = 'Complaint'
AND b.C6_REFERENCE_TYPE = ('Citizen Complaint')
AND c.G6_DOC_DES = ('Insp Completed')

ORDER BY c.G6_STATUS_DD DESC