SELECT
Distinct (Row_index + 1) SignNum,
  (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'How Secured'
  ) HowSecured,--*/
  (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'Dimensions'
  ) SignDem, --*/
    (
    SELECT ATTRIBUTE_VALUE
    FROM BAPPSPECTABLE_VALUE BASTV1
    WHERE 1=1
    AND BASTV1.SERV_PROV_CODE = ASIT.SERV_PROV_CODE
    AND BASTV1.B1_PER_ID1 = ASIT.B1_PER_ID1
    AND BASTV1.B1_PER_ID2 = ASIT.B1_PER_ID2
    AND BASTV1.B1_PER_ID3 = ASIT.B1_PER_ID3
    AND BASTV1.REC_STATUS = ASIT.REC_STATUS
    AND BASTV1.ROW_INDEX = ASIT.ROW_INDEX
    AND BASTV1.TABLE_NAME = 'SIGN INFORMATION'
    AND BASTV1.COLUMN_NAME = 'SqFt'
  ) SignSQFT, --*/
  1
FROM bappspectable_value ASIT
WHERE
		1=1
		AND '{?servProv}' = ASIT.SERV_PROV_CODE
		AND '{?perID1}' = ASIT.B1_PER_ID1
		AND '{?perID2}' = ASIT.B1_PER_ID2
		AND '{?perID3}' = ASIT.B1_PER_ID3
		AND '{?recStat}' = ASIT.REC_STATUS
    AND UPPER(ASIT.ATTRIBUTE_VALUE) = 'APPROVED'