SELECT
--======================================
-- Report: Sign Permit
-- Developed by: Accela Inc.
-- Date: 2009-10-05
--======================================
	B.SERV_PROV_CODE, 
    B.B1_PER_ID1, 
    B.B1_PER_ID2, 
    B.B1_PER_ID3, 
    B.REC_STATUS, 
    B.B1_ALT_ID,
    B.B1_SPECIAL_TEXT,
    TO_CHAR(GP.G6_APP_DD, 'DD-MON-YYYY') IssuedDate,
   (
        CASE WHEN GP.GA_FNAME IS NOT NULL THEN UPPER(GP.GA_FNAME) || ' ' ELSE '' END ||
        CASE WHEN GP.GA_MNAME IS NOT NULL THEN UPPER(GP.GA_MNAME) || ' ' ELSE '' END ||
        CASE WHEN GP.GA_LNAME IS NOT NULL THEN UPPER(GP.GA_LNAME) || ' ' ELSE '' END
    ) IssuedBy,
	(
		SELECT
			CASE WHEN B3A.B1_HSE_NBR_START IS NOT NULL THEN B3A.B1_HSE_NBR_START||' ' ELSE '' END ||
			CASE WHEN B3A.B1_STR_NAME IS NOT NULL THEN B3A.B1_STR_NAME||' ' ELSE '' END ||
			CASE WHEN B3A.B1_STR_SUFFIX IS NOT NULL THEN B3A.B1_STR_SUFFIX||' ' ELSE '' END ||
			CASE WHEN B3A.B1_STR_SUFFIX_DIR IS NOT NULL THEN B3A.B1_STR_SUFFIX_DIR||' ' ELSE '' END ||
			CASE WHEN B3A.B1_UNIT_TYPE IS NOT NULL THEN B3A.B1_UNIT_TYPE||' ' ELSE '' END ||
			CASE WHEN B3A.B1_UNIT_START IS NOT NULL THEN B3A.B1_UNIT_START||' ' ELSE '' END
		FROM
			B3ADDRES B3A
		WHERE
			1=1
			AND B.SERV_PROV_CODE = B3A.SERV_PROV_CODE AND B.REC_STATUS = B3A.REC_STATUS
			AND B.B1_PER_ID1 = B3A.B1_PER_ID1 AND B.B1_PER_ID2 = B3A.B1_PER_ID2 AND B.B1_PER_ID3 = B3A.B1_PER_ID3
			AND B3A.B1_ADDRESS_NBR = 
			(
				SELECT MIN(B3A1.B1_ADDRESS_NBR)
				FROM B3ADDRES B3A1
				WHERE
					1=1
					AND B.SERV_PROV_CODE = B3A1.SERV_PROV_CODE AND B.REC_STATUS = B3A1.REC_STATUS
					AND B.B1_PER_ID1 = B3A1.B1_PER_ID1 AND B.B1_PER_ID2 = B3A1.B1_PER_ID2 AND B.B1_PER_ID3 = B3A1.B1_PER_ID3
					AND B3A1.B1_PRIMARY_ADDR_FLG = (
						SELECT MAX(B3A2.B1_PRIMARY_ADDR_FLG)
						FROM B3ADDRES B3A2
						WHERE
							1=1
							AND B.SERV_PROV_CODE = B3A2.SERV_PROV_CODE
							AND B.B1_PER_ID1 = B3A2.B1_PER_ID1
							AND B.B1_PER_ID2 = B3A2.B1_PER_ID2
							AND B.B1_PER_ID3 = B3A2.B1_PER_ID3
							AND B.REC_STATUS = B3A2.REC_STATUS
					)
			)
	) JobSite,
	(
		SELECT BCBS.B1_CHECKLIST_COMMENT
		FROM BCHCKBOX BCBS
		WHERE
			BCBS.SERV_PROV_CODE = B.SERV_PROV_CODE AND BCBS.REC_STATUS = B.REC_STATUS
			AND BCBS.B1_PER_ID1 = B.B1_PER_ID1 AND BCBS.B1_PER_ID2 = B.B1_PER_ID2 AND BCBS.B1_PER_ID3 = B.B1_PER_ID3
			AND BCBS.B1_CHECKBOX_TYPE = 'ZONING' AND BCBS.B1_CHECKBOX_DESC = 'Zoning1'
	) Zoning,
	(
		SELECT BCBS.B1_CHECKLIST_COMMENT
		FROM BCHCKBOX BCBS
		WHERE
			BCBS.SERV_PROV_CODE = B.SERV_PROV_CODE AND BCBS.REC_STATUS = B.REC_STATUS
			AND BCBS.B1_PER_ID1 = B.B1_PER_ID1 AND BCBS.B1_PER_ID2 = B.B1_PER_ID2 AND BCBS.B1_PER_ID3 = B.B1_PER_ID3
			AND BCBS.B1_CHECKBOX_TYPE = 'ZONING' AND BCBS.B1_CHECKBOX_DESC = 'NPU'
	) NPU,--*/
	(
		SELECT BCBS.B1_CHECKLIST_COMMENT
		FROM BCHCKBOX BCBS
		WHERE
			BCBS.SERV_PROV_CODE = B.SERV_PROV_CODE AND BCBS.REC_STATUS = B.REC_STATUS
			AND BCBS.B1_PER_ID1 = B.B1_PER_ID1 AND BCBS.B1_PER_ID2 = B.B1_PER_ID2 AND BCBS.B1_PER_ID3 = B.B1_PER_ID3
			AND BCBS.B1_CHECKBOX_TYPE = 'ZONING' AND BCBS.B1_CHECKBOX_DESC = 'Council District'
	) CouncilDistrict,--*/
	--BCB.*,
    (
        SELECT B3P.B1_PARCEL_NBR
        FROM   B3PARCEL B3P
        WHERE  B3P.SERV_PROV_CODE=B.SERV_PROV_CODE AND
               B3P.B1_PER_ID1=B.B1_PER_ID1 AND
               B3P.B1_PER_ID2=B.B1_PER_ID2 AND
               B3P.B1_PER_ID3=B.B1_PER_ID3 AND
               ROWNUM<2
    ) B1_PARCEL_NBR,
  1
FROM
	B1PERMIT B
	INNER JOIN BPERMIT_DETAIL BD ON
		B.SERV_PROV_CODE = BD.SERV_PROV_CODE
		AND B.B1_PER_ID1 = BD.B1_PER_ID1
		AND B.B1_PER_ID2 = BD.B1_PER_ID2
		AND B.B1_PER_ID3 = BD.B1_PER_ID3
		AND B.REC_STATUS = BD.REC_STATUS
    INNER JOIN GPROCESS GP ON
        B.SERV_PROV_CODE = GP.SERV_PROV_CODE
		AND B.B1_PER_ID1 = GP.B1_PER_ID1
		AND B.B1_PER_ID2 = GP.B1_PER_ID2
		AND B.B1_PER_ID3 = GP.B1_PER_ID3
		AND B.REC_STATUS = GP.REC_STATUS
        AND GP.SD_PRO_DES = 'Issue Permit'
        AND GP.SD_APP_DES = 'Issued'
WHERE
	1=1
    AND B.SERV_PROV_CODE = 'ATLANTA_GA'
	AND BD.BALANCE <= 0
	--======================================
	-- TEST CASE
	--AND B.B1_ALT_ID = 'BS-201700526'
	-- END TEST CASE
	--======================================
	AND B.B1_ALT_ID = upper('{?CaseNum}')