true ^ pArray = new Array(); pArray = getGISBufferInfo("ATLANTA_GA","Zoning Districts",-10,"ZONING");mArray = new Array(); mArray = getGISBufferInfo("ATLANTA_GA","Overlay Zoning Districts",-10,"LABEL");
pArray.length > 0 ^ editAppSpecific("Zoning 1", pArray[0]["ZONING"]);
pArray.length > 1 ^ editAppSpecific("Zoning 2", pArray[1]["ZONING"]);
pArray.length > 2 ^ editAppSpecific("Zoning 3", pArray[2]["ZONING"]);
mArray.length > 0 ^ editAppSpecific("Zoning Overlay", mArray[0]["LABEL"]);
mArray.length > 1 ^ editAppSpecific("Zoning Overlay", mArray[0]["LABEL"]+", "+mArray[1]["LABEL"]);
true ^ npuArray = new Array(); npuArray = getGISBufferInfo("ATLANTA_GA","NPU",-1,"NPU","NEXT_MEET","ZONING","ZONING_PHONE","ZONING_EMAIL","LOCATION","ADDRESS","TIME");
npuArray != null && npuArray.length > 0 ^ editAppSpecific("NPU",npuArray[0]["NPU"]); editAppSpecific("NPU date",npuArray[0]["NEXT_MEET"]); editAppSpecific("NPU contact",npuArray[0]["ZONING"]); editAppSpecific("NPU phone",npuArray[0]["ZONING_PHONE"]); editAppSpecific("NPU email",npuArray[0]["ZONING_EMAIL"]); editAppSpecific("NPU location",npuArray[0]["LOCATION"]); editAppSpecific("NPU time",npuArray[0]["TIME"]); editAppSpecific("NPU address",npuArray[0]["ADDRESS"]);
true ^ editAppSpecific("Land Lot",getGISInfo("ATLANTA_GA","Land Lots","LANDLOT")); editAppSpecific("District",getGISInfo("ATLANTA_GA","Land Lots","DIST_NUM"));
true ^ editAppSpecific("SPI Zoning",getGISInfo("ATLANTA_GA","SPI Overlay","LABEL"));
true ^ editAppSpecific("Beltline District",getGISInfo("ATLANTA_GA","Beltline Overlay","LABEL"));
true ^ editAppSpecific("Council District",getGISInfo("ATLANTA_GA","City Council Districts", "DISTRICT"));
true ^ editAppSpecific("CDP Land Use",getGISInfo("ATLANTA_GA","Future Land Use", "LANDUSE"));
true ^ editAppSpecific("Flood Zone 1",getGISInfo("ATLANTA_GA","DFIRM Flood Hazard Grid", "FLD_ZONE"));
true ^ editAppSpecific("Flood Zone 2",getGISInfo("ATLANTA_GA","Combined Sewer Overflow Area", "CSODRAIN"));
true ^ editAppSpecific("Historic Building and Properties",getGISInfo("ATLANTA_GA","Landmark Buildings and Sites", "BUILDING_N"));
true ^ editAppSpecific("Building Zone",getGISInfo("ATLANTA_GA","Building Zones", "ZONE"));
true ^ editAppSpecific("Plumbing Zone",getGISInfo("ATLANTA_GA","Plumbing Zones", "ZONE"));
true ^ editAppSpecific("HVAC Zone",getGISInfo("ATLANTA_GA","HVAC Zones", "ZONE"));
true ^ editAppSpecific("Electrical Zone",getGISInfo("ATLANTA_GA","Electrical Zones", "ZONE"));
true ^ editAppSpecific("Arborist Zone",getGISInfo("ATLANTA_GA","Arborist Zones", "ZONE"));
true ^ editAppSpecific("NPU Neighborhood",getGISInfo("ATLANTA_GA","Code Compliance Inspection Zones", "DCA")); editAppSpecific("NPU Insp Supervisor",getGISInfo("ATLANTA_GA","Code Compliance Inspection Zones","SUPERVISOR"));
true ^ npuArray = new Array(); npuArray = getGISBufferInfo("ATLANTA_GA","NPU Associated 1","-10","NPU","ZONING","ZONING_PHONE","ZONING_EMAIL");
npuArray.length > 0 ^ editAppSpecific("NPU Associated 1", npuArray[0]["NPU"]); editAppSpecific("NPU1 Contact", npuArray[0]["ZONING"]); editAppSpecific("NPU1 phone", npuArray[0]["ZONING_PHONE"]); editAppSpecific("NPU1 email", npuArray[0]["ZONING_EMAIL"]);
npuArray.length > 1 ^ editAppSpecific("NPU Associated 2", npuArray[1]["NPU"]); editAppSpecific("NPU2 contact", npuArray[1]["ZONING"]); editAppSpecific("NPU2 phone", npuArray[1]["ZONING_PHONE"]); editAppSpecific("NPU2 email", npuArray[1]["ZONING_EMAIL"]);
npuArray.length > 2 ^ editAppSpecific("NPU Associated 3", npuArray[2]["NPU"]); editAppSpecific("NPU3 contact", npuArray[2]["ZONING"]); editAppSpecific("NPU3 phone", npuArray[2]["ZONING_PHONE"]); editAppSpecific("NPU3 email", npuArray[2]["ZONING_EMAIL"]);
true ^ editAppSpecific("NPU Neighborhood",getGISInfo("ATLANTA_GA","Code Enforcement Zones", "DCA")); editAppSpecific("NPU Insp Supervisor",getGISInfo("ATLANTA_GA","Code Enforcement Zones","SUPERVISOR"));
true ^ editAppSpecific("NPU Neighborhood",getGISInfo("ATLANTA_GA","Code Enforcement Zones", "DCA")); editAppSpecific("NPU Insp Supervisor",getGISInfo("ATLANTA_GA","Code Enforcement Zones","SUPERVISOR")); editAppSpecific("Inspector",getGISInfo("ATLANTA_GA","Code Enforcement Zones","INSPECTOR"));
true ^ editAppSpecific("Neighborhood",getGISInfo("ATLANTA_GA","Neighborhoods", "Name"));
true ^ editAppSpecific("Battalion",getGISInfo("ATLANTA_GA","Fire Battalion", "BATT_ID"));
true ^ moraArray = new Array(); moraArray = getGISBufferInfo("ATLANTA_GA","Building Moratoriums",-1,"NAME");
moraArray.length > 0 && moraArray[0]["NAME"] == "Beltline Storage" ^ addStdCondition("Moratoriums","Beltline Storage Moratorium");
moraArray.length > 0 && moraArray[0]["NAME"] == "Buckhead Parking Overlay" ^ addStdCondition("Moratoriums","Buckhead Parking Moratorium");
moraArray.length > 0 && moraArray[0]["NAME"] == "Tuxedo Park" ^ addStdCondition("Moratoriums","Tuxedo Park Moratorium");
moraArray.length > 0 && moraArray[0]["NAME"] == "Westside Revive" ^ addStdCondition("Moratoriums","Westside Revive Moratorium");
moraArray.length > 1 && moraArray[1]["NAME"] == "Buckhead Parking Overlay" ^ addStdCondition("Moratoriums","Buckhead Parking Moratorium");
moraArray.length > 1 && moraArray[1]["NAME"] == "Beltline Storage" ^ addStdCondition("Moratoriums","Beltline Storage Moratorium");
moraArray.length > 0 ^ branch("Moratoriums");
true ^ IZArray = new Array(); IZArray = getGISBufferInfo("ATLANTA_GA","Inclusionary Zoning SubAreas",-1,"NAME","BPA_SUBAREA");
IZArray.length > 0 ^ editAppSpecific("Inclusionary Zoning", IZArray[0]["NAME"]); editAppSpecific("BPA Subarea", IZArray[0]["BPA_SUBAREA"]); comment("Permit in Inclusionary Zoning Area. <BR>"); showMessage = true;
IZArray.length > 1 ^ comment("Permit in more than one Inclusionary Zoning area. <BR>"); showMessage = true;