SELECT
    G6A.G6_ACT_TYP INSPTYPE,
    G6A.G6_STATUS INSPSTATUS,
    G6A.G6_STATUS_DD INSPDATE,
    
    
    (CASE WHEN G6A.GA_FNAME IS NOT NULL THEN G6A.GA_FNAME || ' ' ELSE '' END ||
    CASE WHEN G6A.GA_MNAME IS NOT NULL THEN G6A.GA_MNAME || ' ' ELSE '' END ||
    CASE WHEN G6A.GA_LNAME IS NOT NULL THEN G6A.GA_LNAME ELSE '' END) INSPECTORNAME,
    
    BAC.TEXT INSPRESULTCOMNT

    
FROM B1PERMIT B
    
    INNER JOIN G6ACTION G6A ON 1=1
        AND B.SERV_PROV_CODE = G6A.SERV_PROV_CODE
        AND B.B1_PER_ID1 = G6A.B1_PER_ID1
        AND B.B1_PER_ID2 = G6A.B1_PER_ID2
        AND B.B1_PER_ID3 = G6A.B1_PER_ID3
        
    LEFT OUTER JOIN BACTIVITY_COMMENT BAC ON 1=1
        AND B.SERV_PROV_CODE = BAC.SERV_PROV_CODE
        AND B.B1_PER_ID1 = BAC.B1_PER_ID1
        AND B.B1_PER_ID2 = BAC.B1_PER_ID2
        AND B.B1_PER_ID3 = BAC.B1_PER_ID3
        AND G6A.G6_ACT_NUM = BAC.G6_ACT_NUM
        AND BAC.COMMENT_TYPE = 'Inspection Result Comment'
        
WHERE 1=1
--    AND B.B1_ALT_ID = UPPER('{?capid}')
    AND B.B1_ALT_ID = '17CAP-00000290'
    AND G6A.REC_STATUS = 'A'
    
ORDER BY G6A.G6_STATUS_DD DESC