SELECT
  --SUBQUERY LINKS
--b.serv_prov_code,
--b.b1_per_id1,
--b.b1_per_id2,
--b.b1_per_id3,
  --RECORD INFO
--  B.B1_ALT_ID AS RECORD,
(B.B1_PER_GROUP || '/' || B.B1_PER_TYPE || '/' || B.B1_PER_SUB_TYPE || '/' || B.B1_PER_CATEGORY) AS RECORD_TYPE,
count((B.B1_PER_GROUP || '/' || B.B1_PER_TYPE || '/' || B.B1_PER_SUB_TYPE || '/' || B.B1_PER_CATEGORY)) AS RECORD_TYPE_COUNT
/*  CASE WHEN B.B1_SPECIAL_TEXT IS NOT NULL THEN B.B1_SPECIAL_TEXT ELSE '' END AS RECORD_NAME,
  (SELECT CASE WHEN B3A.B1_STR_NAME IS NOT NULL THEN B3A.B1_STR_NAME ELSE '' END
  FROM B3ADDRES B3A
		WHERE
			B.SERV_PROV_CODE = B3A.SERV_PROV_CODE AND B.REC_STATUS = B3A.REC_STATUS
			AND B.B1_PER_ID1 = B3A.B1_PER_ID1 AND B.B1_PER_ID2 = B3A.B1_PER_ID2 AND B.B1_PER_ID3 = B3A.B1_PER_ID3
			AND B1_ADDRESS_NBR = (
					SELECT MIN(B1_ADDRESS_NBR)
					FROM B3ADDRES B3A1
					WHERE
						1=1
						AND B.SERV_PROV_CODE = B3A1.SERV_PROV_CODE AND B.REC_STATUS = B3A1.REC_STATUS
						AND B.B1_PER_ID1 = B3A1.B1_PER_ID1 AND B.B1_PER_ID2 = B3A1.B1_PER_ID2 AND B.B1_PER_ID3 = B3A1.B1_PER_ID3
						AND B3A1.B1_PRIMARY_ADDR_FLG = (
							SELECT MAX(B3A2.B1_PRIMARY_ADDR_FLG)
							FROM B3ADDRES B3A2
							WHERE
								1=1
								AND B.SERV_PROV_CODE = B3A2.SERV_PROV_CODE AND B.REC_STATUS = B3A2.REC_STATUS
								AND B.B1_PER_ID1 = B3A2.B1_PER_ID1 AND B.B1_PER_ID2 = B3A2.B1_PER_ID2 AND B.B1_PER_ID3 = B3A2.B1_PER_ID3
                                                       )
                                 )
  ) AS STREET_NAME,

	(
		SELECT
			CASE WHEN B3A.B1_HSE_NBR_START IS NOT NULL THEN B3A.B1_HSE_NBR_START||' ' ELSE '' END||
			CASE WHEN B3A.B1_STR_NAME IS NOT NULL THEN B3A.B1_STR_NAME||' ' ELSE '' END ||
			CASE WHEN B3A.B1_STR_SUFFIX IS NOT NULL THEN B3A.B1_STR_SUFFIX||' ' ELSE '' END ||
			CASE WHEN B3A.B1_STR_SUFFIX_DIR IS NOT NULL THEN B3A.B1_STR_SUFFIX_DIR||' ' ELSE '' END ||
			CASE WHEN B3A.B1_SITUS_CITY IS NOT NULL THEN B3A.B1_SITUS_CITY||', ' ELSE '' END ||
			CASE WHEN B3A.B1_SITUS_STATE IS NOT NULL THEN B3A.B1_SITUS_STATE||' ' ELSE '' END ||
			CASE WHEN B3A.B1_SITUS_ZIP IS NOT NULL THEN B3A.B1_SITUS_ZIP||' ' ELSE '' END
		FROM B3ADDRES B3A
		WHERE
			B.SERV_PROV_CODE = B3A.SERV_PROV_CODE AND B.REC_STATUS = B3A.REC_STATUS
			AND B.B1_PER_ID1 = B3A.B1_PER_ID1 AND B.B1_PER_ID2 = B3A.B1_PER_ID2 AND B.B1_PER_ID3 = B3A.B1_PER_ID3
			AND B1_ADDRESS_NBR = (
					SELECT MIN(B1_ADDRESS_NBR)
					FROM B3ADDRES B3A1
					WHERE
						1=1
						AND B.SERV_PROV_CODE = B3A1.SERV_PROV_CODE AND B.REC_STATUS = B3A1.REC_STATUS
						AND B.B1_PER_ID1 = B3A1.B1_PER_ID1 AND B.B1_PER_ID2 = B3A1.B1_PER_ID2 AND B.B1_PER_ID3 = B3A1.B1_PER_ID3
						AND B3A1.B1_PRIMARY_ADDR_FLG = (
							SELECT MAX(B3A2.B1_PRIMARY_ADDR_FLG)
							FROM B3ADDRES B3A2
							WHERE
								1=1
								AND B.SERV_PROV_CODE = B3A2.SERV_PROV_CODE AND B.REC_STATUS = B3A2.REC_STATUS
								AND B.B1_PER_ID1 = B3A2.B1_PER_ID1 AND B.B1_PER_ID2 = B3A2.B1_PER_ID2 AND B.B1_PER_ID3 = B3A2.B1_PER_ID3
						)
			)
	) AS ADDRESS

  --INSPECTIONS
     G.G6_ACT_TYP                AS INSPECTION_TYPE
     ,G.G6_ACT_DD                 AS SCHEDULED_DATE
     ,G.G6_COMPL_DD               AS INSPECTION_DATE
     ,(  CASE WHEN G.GA_FNAME IS NOT NULL AND G.GA_LNAME IS NOT NULL 
        THEN
          (CASE WHEN G.GA_MNAME IS NULL THEN G.GA_FNAME||' '||G.GA_LNAME ELSE G.GA_FNAME||' '||G.GA_MNAME||' '||G.GA_LNAME END)
        ELSE
          (CASE WHEN U.MNAME IS NULL THEN U.FNAME||' '||U.LNAME ELSE U.FNAME||' '||U.MNAME||' '||U.LNAME END)
      END
  )                               AS INSPECTOR_NAME_FML#
     ,(  CASE WHEN G.G6_STATUS = 'Scheduled' OR ( G.G6_ACT_DD IS NULL AND G.G6_COMPL_DD IS NULL )
        THEN NULL
        ELSE G.G6_STATUS     
      END
  )                               AS RESULT_
  --BCHCKBOX
    ,D.B1_CHECKLIST_COMMENT AS WORKSTREAM
    ,E.B1_CHECKLIST_COMMENT AS SCOPE_CODE
*/
  
  FROM B1PERMIT B
  LEFT JOIN
    G6ACTION G
    ON  B.SERV_PROV_CODE = G.SERV_PROV_CODE
    AND B.B1_PER_ID1 = G.B1_PER_ID1
    AND B.B1_PER_ID2 = G.B1_PER_ID2
    AND B.B1_PER_ID3 = G.B1_PER_ID3
    AND G.REC_STATUS = 'A'
  
  LEFT JOIN
    PUSER U
    ON  G.SERV_PROV_CODE = U.SERV_PROV_CODE
    AND G.GA_USERID = U.GA_USER_ID
    
  LEFT OUTER JOIN
    BCHCKBOX D
    ON  B.SERV_PROV_CODE = D.SERV_PROV_CODE
    AND B.B1_PER_ID1 = D.B1_PER_ID1
    AND B.B1_PER_ID2 = D.B1_PER_ID2
    AND B.B1_PER_ID3 = D.B1_PER_ID3
    AND D.B1_CHECKBOX_DESC = 'Workstream'
    AND D.REC_STATUS = 'A'
    
  LEFT OUTER JOIN
    BCHCKBOX E
    ON  B.SERV_PROV_CODE = E.SERV_PROV_CODE
    AND B.B1_PER_ID1 = E.B1_PER_ID1
    AND B.B1_PER_ID2 = E.B1_PER_ID2
    AND B.B1_PER_ID3 = E.B1_PER_ID3
    AND E.B1_CHECKBOX_DESC = 'Scope Code'
    AND E.REC_STATUS = 'A'
    
  
  
  WHERE 
    B.SERV_PROV_CODE = 'ATLANTA_GA'
    AND B.B1_PER_GROUP = 'Building' AND B.REC_STATUS = 'A'
    AND (
            (
            G.G6_COMPL_DD >= {?startDate}
        and G.G6_COMPL_DD < {?endDate} + 1
            )
        OR
            (
            G.G6_ACT_DD >= {?startDate}
        and G.G6_ACT_DD < {?endDate} + 1
            )
        )
  --AND G.G6_COMPL_DD >= TO_DATE('08/01/2017','MM/DD/YYYY')
  --and G.G6_COMPL_DD < TO_DATE('08/04/2017','MM/DD/YYYY') + 1
   
  GROUP BY
    B.B1_PER_GROUP,
    B.B1_PER_TYPE,
    B.B1_PER_SUB_TYPE,
    B.B1_PER_CATEGORY
    
  ORDER BY
    B.B1_PER_GROUP,
    B.B1_PER_TYPE,
    B.B1_PER_SUB_TYPE,
    B.B1_PER_CATEGORY