SELECT --*

A.SERV_PROV_CODE,
A.B1_PER_ID1,
A.B1_PER_ID2,
A.B1_PER_ID3,
A.B1_PER_GROUP                      AS "GROUP",
A.B1_PER_TYPE                       AS "TYPE",
A.B1_PER_SUB_TYPE                   AS "SUBTYPE",
A.B1_PER_CATEGORY                   AS "CATEGORY",
A.B1_ALT_ID                         AS PermitNum,
A.B1_APPL_STATUS                    AS AppStatus,
A.B1_SPECIAL_TEXT                   AS ProjName,
TO_CHAR(A.B1_FILE_DD,'MM/DD/YYYY')  AS OpenDate,

CASE WHEN B.G6_STAT_DD || B.B1_DUE_DD IS NULL
     THEN 'Due date not determined'
     WHEN B.G6_STAT_DD IS NULL
     THEN 'Due ' || TO_CHAR(B.B1_DUE_DD,'MM/DD/YYYY')
     ELSE TO_CHAR(B.G6_STAT_DD,'MM/DD/YYYY') END 
                                    AS TaskStatusDate,
B.SD_PRO_DES                        AS Task,
B.SD_APP_DES                        AS TaskStatus,
CASE WHEN B.SD_COMMENT = 'undefined' then NULL
     ELSE B.SD_COMMENT END          AS TaskStatusComment,
B.SD_PRO_ID1                        AS TaskID,


CASE WHEN B.GA_LNAME IS NULL
     THEN B.ASGN_FNAME || ' ' || B.ASGN_LNAME
     ELSE B.GA_FNAME || ' ' || B.GA_LNAME
     END                            AS Reviewer, 

COALESCE(S.GA_EMPLOY_PH1, S.GA_EMPLOY_PH2)
                                    AS ReviewerPhone,

S.GA_EMAIL AS ReviewerEmail

FROM B1PERMIT A

INNER JOIN BPERMIT_DETAIL PD ON 1=1
AND A.SERV_PROV_CODE = PD.SERV_PROV_CODE
AND A.B1_PER_ID1 = PD.B1_PER_ID1
AND A.B1_PER_ID2 = PD.B1_PER_ID2
AND A.B1_PER_ID3 = PD.B1_PER_ID3

LEFT OUTER JOIN GPROCESS B ON 1=1
AND A.SERV_PROV_CODE = B.SERV_PROV_CODE
AND A.B1_PER_ID1 = B.B1_PER_ID1
AND A.B1_PER_ID2 = B.B1_PER_ID2
AND A.B1_PER_ID3 = B.B1_PER_ID3
AND (B.SD_CHK_LV1 = 'Y' OR B.SD_CHK_LV2 = 'Y')
/*
LEFT OUTER JOIN GPROCESS_HISTORY C ON 1=1
AND A.SERV_PROV_CODE = C.SERV_PROV_CODE
AND A.B1_PER_ID1 = C.B1_PER_ID1
AND A.B1_PER_ID2 = C.B1_PER_ID2
AND A.B1_PER_ID3 = C.B1_PER_ID3
AND B.SD_PRO_DES = C.SD_PRO_DES
*/

LEFT OUTER JOIN G3STAFFS S ON 1=1 AND
CASE WHEN B.GA_FNAME IS NULL THEN B.ASGN_FNAME ELSE B.GA_FNAME END = S.GA_FNAME AND
	CASE WHEN B.GA_LNAME IS NULL THEN B.ASGN_LNAME ELSE B.GA_LNAME END = S.GA_LNAME AND
	S.REC_STATUS = 'A' AND
	S.GA_DIVISION_CODE != 'PUBLIC'

WHERE 1=1
--AND A.B1_ALT_ID = 'BB-201704476'
AND A.B1_ALT_ID = ANY {?ID}
AND A.SERV_PROV_CODE = 'ATLANTA_GA'

ORDER BY B.REC_DATE