--SELECT *
--SELECT COUNT (*)
SELECT DISTINCT
    B.L1_PARCEL_NBR AS "Parcel",
    NVL(C.L1_HSE_NBR_START,'') || NVL(C.L1_STR_DIR,'') AS "Street Number",
    NVL(C.L1_STR_PREFIX || ' ','') || NVL(C.L1_STR_NAME || ' ','') || NVL(C.L1_STR_SUFFIX || ' ','') || NVL(C.L1_STR_SUFFIX_DIR || ', ','') ||
    NVL(C.L1_SITUS_CITY || ', ','') || NVL(C.L1_SITUS_STATE || ' ','') || NVL(C.L1_SITUS_ZIP,'') AS "Street/City/ST/Zip",
--    NVL(C.L1_UNIT_START,'') AS "Unit",
    D.L1_RESIDENTIAL_UNITS AS "SE Number of Units",
    D.L1_NAME AS "SE Name",
    D.L1_NUMBER AS "SE Number",
    D.L1_GROUP AS "SE Type",
    D.L1_STATUS AS "SE Status",
    TO_CHAR(D.L1_STATUS_DATE,'MM/DD/YYYY') AS "SE Status Date",
    C.L1_PRIMARY_ADDR_FLG AS "Primary Address"



FROM XPARADDR A

INNER JOIN L3PARCEL B ON
A.L1_PARCEL_NBR = B.L1_PARCEL_NBR

INNER JOIN L3ADDRES C ON
A.L1_ADDRESS_NBR = C.L1_ADDRESS_NBR

INNER JOIN L3STRU_ESTA D ON
A.L1_PARCEL_NBR = SUBSTR(D.L1_NUMBER,0,14)


WHERE
   (D.L1_NAME LIKE '%MULTI%' OR
    D.L1_NAME LIKE '%APARTMENT%' OR
    D.L1_NAME LIKE '%CONDO%' OR
    D.L1_NAME LIKE '%TOWNH%' OR
    D.L1_NAME LIKE '%TOWN_H%' OR
    D.L1_NAME LIKE '%APT%' OR
    D.L1_NAME LIKE '%LOFTS%')
or
    D.L1_RESIDENTIAL_UNITS >= 6;