/*SELECT A.B1_ALT_ID AS PARENT,
C.B1_ALT_ID AS CHILD


SELECT DISTINCT
A.B1_ALT_ID,
A.B1_PER_ID1,
A.B1_PER_ID2,
A.B1_PER_ID3,
A.REC_STATUS,
A.SERV_PROV_CODE
*/

SELECT DISTINCT
A.B1_ALT_ID AS "Building Permit",
CASE WHEN C.B1_PER_TYPE = 'Arborist' THEN C.B1_ALT_ID ELSE '' END AS "Related Arborist Permit Record",
CASE WHEN C.B1_PER_TYPE = 'Impact Fees' THEN C.B1_ALT_ID ELSE '' END AS "Related Impact Fees Record",
IC.BALANCE_DUE AS "Fees Due",
A.B1_APPL_STATUS AS "Record Status"

FROM B1PERMIT A

INNER JOIN XAPP2REF X ON 1=1
AND A.B1_PER_ID1 = X.B1_MASTER_ID1
AND A.B1_PER_ID3 = X.B1_MASTER_ID3

INNER JOIN B1PERMIT C ON 1=1
AND X.B1_PER_ID1 = C.B1_PER_ID1
AND X.B1_PER_ID3 = C.B1_PER_ID3

INNER JOIN X4FEEITEM_INVOICE XIA ON 1=1
AND A.B1_PER_ID1 = XIA.B1_PER_ID1
AND A.B1_PER_ID3 = XIA.B1_PER_ID3

INNER JOIN F4FEEITEM FA ON 1=1
AND XIA.FEEITEM_SEQ_NBR = FA.FEEITEM_SEQ_NBR
--AND FA.GF_ITEM_STATUS_FLAG = 'INVOICED'

INNER JOIN F4INVOICE IA ON 1=1
AND XIA.INVOICE_NBR = IA.INVOICE_NBR
AND IA.BALANCE_DUE = 0

INNER JOIN X4FEEITEM_INVOICE XIC ON 1=1
AND C.B1_PER_ID1 = XIC.B1_PER_ID1
AND C.B1_PER_ID3 = XIC.B1_PER_ID3

INNER JOIN F4FEEITEM FC ON 1=1
AND XIC.FEEITEM_SEQ_NBR = FC.FEEITEM_SEQ_NBR
AND FC.GF_ITEM_STATUS_FLAG = 'INVOICED'

INNER JOIN F4INVOICE IC ON 1=1
AND XIC.INVOICE_NBR = IC.INVOICE_NBR
AND IC.BALANCE_DUE > 0




WHERE 1=1
--AND A.B1_ALT_ID = 'BB-201605935'
--AND A.B1_PER_TYPE = 'Commercial' AND A.B1_PER_SUB_TYPE = 'New'
AND C.B1_PER_TYPE IN ('Arborist','Impact Fees')
AND A.B1_APPL_STATUS IN ('Issued','Complete')

ORDER BY A.B1_ALT_ID